name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      # https://github.com/NSIS-Dev/github-action-examples
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
      - name: Run NSIS
        run: makensis ./setup/sldshow.nsi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./setup/*.exe
